replicaCount: 1

image:
  repository: bitnami/grafana
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi  # Adjusted to a smaller size for CRC
  storageClass: ""
  annotations: {}

securityContext:
  fsGroup: 1001  # Ensures the container can write to mounted volumes

containers:
  - name: grafana
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001  # Ensures that the container runs with the correct permissions
    volumeMounts:
      - name: grafana-storage
        mountPath: /opt/bitnami/grafana/data
      - name: plugins
        mountPath: /opt/bitnami/grafana/data/plugins

initContainers:
  - name: fix-permissions
    image: busybox
    command: ['sh', '-c', 'chown -R 1001:1001 /opt/bitnami/grafana/data && chmod -R 775 /opt/bitnami/grafana/data']
    volumeMounts:
      - name: grafana-storage
        mountPath: /opt/bitnami/grafana/data

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  timeoutSeconds: 30
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 10
  failureThreshold: 6

grafana:
  admin:
    existingSecret: ""
  dashboardsConfigMaps: {}
  dashboards:
    enabled: true
  plugins: ""
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

volumes:
  - name: grafana-storage
    persistentVolumeClaim:
      claimName: grafana-pvc
  - name: plugins
    emptyDir: {}
