replicaCount: 1

image:
  repository: bitnami/grafana
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: ""
  annotations: {}
  # Add fsGroup to the persistent volume if supported by the storage class
  mountOptions:
    - dir_mode=0775
    - file_mode=0664
    - uid=1001
    - gid=1001

securityContext:
  enabled: true
  fsGroup: 1001  # Ensures the container can write to mounted volumes
  runAsUser: 1001  # Ensures the container runs as user 1001

initContainers:
  - name: fix-permissions
    image: busybox
    command: ['sh', '-c', 'mkdir -p /opt/bitnami/grafana/data/plugins && chown -R 1001:1001 /opt/bitnami/grafana/data/plugins && chmod -R 775 /opt/bitnami/grafana/data/plugins']
    volumeMounts:
      - name: grafana-storage
        mountPath: /opt/bitnami/grafana/data

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 128Mi

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  timeoutSeconds: 30
  failureThreshold: 6

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  timeoutSeconds: 10
  failureThreshold: 6

grafana:
  admin:
    existingSecret: ""
  dashboardsConfigMaps: {}
  dashboards:
    enabled: true
  plugins: ""
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

volumeMounts:
  - name: grafana-storage
    mountPath: /opt/bitnami/grafana/data

volumes:
  - name: grafana-storage
    persistentVolumeClaim:
      claimName: grafana-pvc
